### ISSUE TITLE
 Can not install on LiteOn m2 ssd

### ISSUE THREAD

**Issue by VoltIcaRus** [novaspirit/macpanda#4]
First, I do not have a Mac.
So from the first time I tried the Hackintosh
I have to do some annoying things about making usb boot for about 2 days.
Now it goes to the install screen
I can not find my ssd on disk utality
https://github.com/RehabMan/patch-nvme
I thought this would help
Even though I still apply my immature skills
It does not work
Is there a modified file?
I want to use my first Mac
Now I'm exhausted.

**Comment by theopoon** [comment]
That patch shouldn't be needed, Mojave has native nvme support. (since High Sierra)
Did you select show all disk in Disk Utilities menu?
You may like to take a look at https://www.tonymacx86.com/threads/high-sierra-installer-disk-utility-doesnt-see-ssd.235510/

And as normal Hackintosh experience and advise, it is very painful to get things running without enough knowledge on MacOS / PC and a running MacOS device.
if you want to use a Mac, buy a Mac from Apple.
MacOS was never designed that way / it was designed to NOT work on non Apple hardware, some people found Hackintosh fun, most thinks it a pain.

**Comment by VoltIcaRus** [comment]
I'm using the LITEON CX2-1024 and I do not recognize this, so I eventually installed it on 120gb usb, but I run the dislutil list on usb Mac and run the terminal, but it's still not visible. I'm a Latte Panda 800 model.  Do you have advice?

**Comment by VoltIcaRus** [comment]
In addition, if I install Windows on lite on ssd, it will show up well on the clover boot screen and even boot from clover to windows.

**Comment by VoltIcaRus** [comment]
I have solved this problem and still need that patch. I installed the mac on usb and then put the patch into Clover. Thanks.
